apiVersion: v1
kind: Service
metadata:
  name: mysql-flask-contacts
  namespace: flask-contacts
  labels:
    db: flask-contacts-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    db: flask-contacts-mysql
  type: ClusterIP
  clusterIP: 10.96.0.239
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: flask-contacts-mysql
  namespace: flask-contacts
  labels:
    db: flask-contacts-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: flask-contacts-mysql
  template:
    metadata:
      labels:
        db: flask-contacts-mysql
    spec:
      serviceAccountName: flask-contacts-sa
      containers:
      - name: flask-contacts-mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-contacts-sec
              key: db_user_password
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
        - name:  flask-contacts-db-storage
          mountPath: /var/lib/mysql
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 3 
        resources:
          requests:
            memory: "300Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: "300m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
      volumes:
      - name: flask-contacts-db-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-fc
