apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-fc
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/opt/flask_contact"
    server: 192.168.111.135
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-fc
  namespace: flask-contacts
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
